/**
 * ============================================================================
 * src/lib/constants.ts — Application-Wide Constants
 * ============================================================================
 *
 * Centralizes all shared constants for the application.
 *
 * HOW TO CUSTOMIZE:
 *   1. Replace placeholder social links with your actual URLs.
 *   2. Update NAV_SECTIONS to match the sections on your homepage.
 *   3. SUPPORTED_LOCALES and DEFAULT_LOCALE control which language
 *      routes are generated by the i18n middleware.
 *
 * NOTE: Never put secrets or server-only values here — this module
 * may be imported by client-side components.
 * ============================================================================
 */

/** The API endpoint for the contact form submission. */
export const CONTACT_API_ENDPOINT = "/api/contact";

/**
 * Social media profile links for the footer social icons.
 * TODO: Replace these placeholder URLs with your actual social profiles.
 * Remove any entries for platforms you don't use.
 */
export const SOCIAL_LINKS = {
  /** TODO: Replace with your LinkedIn company page URL */
  linkedin: "https://www.linkedin.com/company/YOUR_COMPANY",
  /** TODO: Replace with your Twitter/X handle, or remove if unused */
  twitter: "https://twitter.com/YOUR_HANDLE",
  /** TODO: Replace with your YouTube channel URL, or remove if unused */
  youtube: "https://youtube.com/@YOUR_CHANNEL",
} as const;

/**
 * The sections available in the homepage navigation.
 * These are used as anchor link targets (#section-id).
 * Update to match the id attributes of your section components.
 */
export const NAV_SECTIONS = [
  "features",
  "stats",
  "cta",
  "contact",
] as const;

/**
 * Supported locale codes for the i18n routing middleware.
 * Adding a new locale here requires adding a matching dictionary file
 * in src/lib/dictionaries/<locale>.json.
 * See: TEMPLATE_CUSTOMIZATION.md → Adding a New Locale
 */
export const SUPPORTED_LOCALES = ["en", "tr"] as const;

/** The default locale used when no locale is detected in the URL. */
export const DEFAULT_LOCALE = "en" as const;

/** The site name, read from the environment variable for SSR usage. */
export const SITE_NAME = process.env.NEXT_PUBLIC_SITE_NAME ?? "Your Company Name";
